name: build on Linux

on:
  push:
    branches:
      - develop

  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 25.x

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Linux build tools
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm

      - name: Display tool versions
        run: |
          node --version
          npm --version
          python --version

      - name: Install dependencies
        run: npm ci

      - name: Rebuild native modules
        run: npm rebuild

      - name: Build Linux application
        run: npm run build-linux

      - name: Create ZIP archive
        run: |
          cd dist
          zip -r Deltamod-linux-files.zip linux-unpacked

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: deltamod-linux-unpacked
          path: dist/Deltamod-linux-files.zip